---
MD007:
  indent: 2
MD009/no-trailing-spaces: false
MD013/line-length: false
MD013:
  line_length: 120
MD026:
  punctuation: '.,;:!。，；:'
MD036: false
MD041: false
MD032: false
MD033: false
MD033/no-inline-html: false
MD024: false
MD025: false
