# - Level of verbose logging. 0 is standard, higher numbers are more verbose
# - overridden by passing --verbose / -v
# - default = 0
verbose: 0

# - Remove cached HTTP responses older than cacheTtl seconds old.
#   Specifying 0 clears and disables cache completely
# - overridden by passing --cache-ttl
# - default = 600
cacheTtl: 86400

# - Exit with code 0 even if an error was encountered. True means a non-zero exit
#   code is only issued if validation could be completed successfully and one or
#   more files were invalid
# - overridden by passing --ignore-errors
# - default = false
ignoreErrors: true

customCatalog:
  schemas:
    - name: prettier
      description: prettier
      fileMatch: ['.prettierrc.yaml']
      location: https://json.schemastore.org/prettierrc.json
    - name: megalinter
      description: megalinter
      fileMatch: ['.mega-linter*.yml']
      location: https://raw.githubusercontent.com/megalinter/megalinter/v9.3.0/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
    - name: pre-commit
      description: pre-commit
      fileMatch: ['.pre-commit-config*.yml', '.pre-commit-config*.yaml']
      location: https://json.schemastore.org/pre-commit-config.json
    - name: eslint-json
      description: eslint-json
      fileMatch: ['.eslintrc-json.json']
      location: https://json.schemastore.org/eslintrc.json
    - name: dependabot
      description: dependabot
      fileMatch: ['.github/workflows/dependabot.yml']
      location: https://www.schemastore.org/dependabot-2.0.json
    - name: hugo
      description: hugo
      fileMatch: ['configs/*.yaml']
      location: https://www.schemastore.org/hugo.json
    - name: editorconfig-checker
      description: editorconfig-checker
      fileMatch: ['.editorconfig-checker.json']
      location: https://raw.githubusercontent.com/editorconfig/editorconfig-defaults/refs/heads/master/editorconfig-defaults.schema.json
