---
# Lint the code base and launch unit test at each push or pull request
name: Lint, Test, Build and Deploy
on: # yamllint disable-line rule:truthy
  push:
    # execute when pushing only branches, not tags
    branches:
      - '**'
      # avoid infinite loop for auto created PRs
      - '!update/pre-commit-*'
    tags:
      - '**'
  workflow_dispatch:

# cancel previous build if several pushes
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  COND_PUSH_OR_PR: |-
    ${{
      github.event_name == 'pull_request' ||
      github.event_name == 'push'
    }}

jobs:
  # -------------------------------------------------------
  # Pre-commit
  # -------------------------------------------------------
  pre-commit:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Forces Node 24 runtime
    permissions:
      # needed by guibranco/github-status-action-v2@v1
      statuses: write
    steps:
      - uses: guibranco/github-status-action-v2@v1
        if: ${{ env.COND_PUSH_OR_PR }}
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: build-my-documents
          state: pending

      - name: Checkout
        uses: actions/checkout@v6

      - uses: crazy-max/ghaction-import-gpg@v7
        if: ${{ success() }}
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: actions/create-github-app-token@v3.1.1
        if: ${{ success() }}
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: guibranco/github-status-action-v2@v1
        if: ${{ env.COND_PUSH_OR_PR }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: pre-commit-megalinter
          state: pending

      - name: Set env vars
        id: vars
        # shellcheck disable=SC2129
        run: |
          (
            echo "branch_name=${GITHUB_REF##*/}"
          ) >> "${GITHUB_ENV}"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Transform pre-commit config for GitHub
        if: ${{ success() }}
        run: .github/preCommitGeneration.sh

      - name: Run pre-commit
        uses: j178/prek-action@v2
        id: preCommit
        with:
          extra-args: >-
            -c .pre-commit-config-github.yaml -a --hook-stage manual

      - name: MegaLinter
        id: ml
        if: ${{ !cancelled() }}
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter/flavors/documentation@v9
        # All available variables are described in documentation
        # https://megalinter.io/latest/config-file/
        env:
          # Validates all source when push on master,
          # else just the git diff with master.
          # Override with true if you always want to lint all sources
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEGALINTER_CONFIG: .mega-linter-githubAction.yml
          CI_MODE: 1

      - name: Upload MegaLinter artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: MegaLinter reports
          retention-days: 2
          overwrite: true
          path: |
            megalinter-reports
            mega-linter.log

      - name: MegaLinter/Precommit has updated sources
        if: >
          steps.preCommit.outcome == 'failure' || (
            steps.ml.outputs.has_updated_sources == 1 && (
              env.APPLY_FIXES_EVENT == 'all' ||
              env.APPLY_FIXES_EVENT == github.event_name
            )
          )
        run: |
          echo "COND_UPDATED_SOURCES=true" >> "${GITHUB_ENV}"

      - name: is apply fixes needed ?
        if: >
          env.APPLY_FIXES_MODE == 'pull_request' && (
            github.event_name == 'push' ||
            github.event.pull_request.head.repo.full_name ==
            github.repository
          )
        run: |
          echo "COND_APPLY_FIXES_NEEDED=true" >> "${GITHUB_ENV}"

      - name: Create Pull Request
        id: cpr
        # prettier-ignore
        if: >
          env.COND_UPDATED_SOURCES == 'true' &&
          env.COND_APPLY_FIXES_NEEDED == 'true' &&
          !contains(github.event.head_commit.message, 'skip fix')
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          committer: fchastanet <237869+fchastanet@users.noreply.github.com>
          branch: update/pre-commit-fixes-${{ env.branch_name }}
          delete-branch: true
          title: lint fixes
          commit-message: Auto-update lint fixes
          body: |
            some auto fixes have been generated during pre-commit run
          labels: pre-commit-fixes

      - name: Print Pull request created
        if: |-
          ${{
            steps.cpr.outputs.pull-request-number &&
            steps.cpr.conclusion == 'success'
          }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - uses: guibranco/github-status-action-v2@v1
        if: ${{ env.COND_PUSH_OR_PR }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: pre-commit-megalinter
          state: ${{ job.status }}

  # -------------------------------------------------------
  # Build and deploy documentation
  # -------------------------------------------------------
  build-deploy:
    needs:
      - pre-commit
    # Only run if the pre-commit job succeeded, and if the push is on master branch or if it's a workflow dispatch event
    if: |-
      ${{
        needs.pre-commit.result == 'success' &&
        (
          github.ref == 'refs/heads/master' ||
          github.event_name == 'workflow_dispatch'
        )
      }}
    uses: fchastanet/my-documents/.github/workflows/build-site-action.yml@master
    with:
      site-name: 'my-documents'
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
