---
name: Pre-commit run
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # https://crontab.cronhub.io/
    - cron: '30 10 * * *'
jobs:
  run:
    runs-on: ubuntu-22.04
    permissions:
      # needed by ouzi-dev/commit-status-updater@v2
      statuses: write
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: pip install pre-commit

      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: lint
          status: pending

      - name: Run pre-commit
        run: pre-commit run -a --hook-stage manual

      - name: Archive results
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: linter-reports
          path: |
            megalinter-reports/**

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update/pre-commit-fixes
          title: lint fixes
          commit-message: Auto-update lint fixes
          body: |
            some auto fixes have been generated during pre-commit run
          labels: updates

      - uses: ouzi-dev/commit-status-updater@v2
        if: always()
        with:
          name: lint
          status: ${{ job.status }}
